spring.datasource.url=jdbc:mysql://localhost:3306/acme
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

jwt.secret=acme-airlines-project
jwt.expiration=36000
